#!/bin/bash
#This script is created to get bi-directional MTR from our machine to monitoring box
#Made by henry.lee@unity3d.com
#Version 2.0.1

##Setting variable##
SSH_ARGS="-o StrictHostKeyChecking=no -o ConnectTimeout=10"
SH="ssh $SSH_ARGS"
IP=${1}
Green='\033[0;32m'
Yellow='\033[1;33m'
Red='\033[1;31m'
NC='\033[0m'
mbox=${2}
opt=${3}

##Code begins here##

#Main Condition

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        echo "---------------------------------"
        echo "[I] LOOK BELOW FOR HOW TO USE"
        echo "./mtr Machine_IP Monitor_Location_ID"
        printf "${Red} Bare Metal Example${NC}"
        echo " ./mtr-tool 8.8.8.8  DAL"
        echo " "
        printf "${Red} GCP Proxy Example${NC}"
        echo " ./mtr-tool 8.8.8.8 zbx-proxy-asia-east2-c"
        echo " "
        echo "*Options"
        echo " "
        echo "-h, --help HELP!!!"
        echo "-U  use UDP instead of ICMP echo"
        echo "-T  use TCP instead of ICMP echo"
        echo " "
        echo "*LOCATION ID"
        printf ${Yellow}
        echo " DAL = Dallas        142.0.204.76"
        echo " AMS = Amsterdam     172.255.235.68"
        echo " MOS = Moscow        88.212.242.156"
        echo " SIG = Singapore     103.23.210.188"
        echo " SJ  = San Jose      209.191.164.177"
        echo " SYD = Sydeny        135.90.89.184"
        echo " SP  = Sao Paulo     169.57.142.117"
        echo " WDC = Washington DC 66.242.12.70"
        echo " "
        printf "${NC}*Google Proxy ${Yellow}"
        echo " "
        echo " zbx-proxy-asia-east2-c            34.96.175.93"
        echo " zbx-proxy-asia-southeast1-c       34.126.115.225"
        echo " zbx-proxy-australia-southeast1-c  34.116.91.115"
        echo " zbx-proxy-europe-north1-c         35.228.223.23"
        echo " zbx-proxy-europe-west4-c          34.91.110.45"
        echo " zbx-proxy-southamerica-east1-c    34.95.152.232"
        echo " zbx-proxy-us-central1-c           35.238.138.122"
        echo " zbx-proxy-us-east4-a              35.245.34.190"
        echo " zbx-proxy-us-west2-c              34.94.241.217"
        echo " infra-1.prod.multiplay.farm       85.236.96.105"
        printf ${NC}
        echo "---------------------------------"
        exit 255
fi



if [[ ! "$IP" =~ (([01]{,1}[0-9]{1,2}|2[0-4][0-9]|25[0-5])\.([01]{,1}[0-9]{1,2}|2[0-4][0-9]|25[0-5])\.([01]{,1}[0-9]{1,2}|2[0-4][0-9]|25[0-5])\.([01]{,1}[0-9]{1,2}|2[0-4][0-9]|25[0-5]))$ ]]; then
        printf $Red"Please insert correct IP format 8.8.8.8"$NC
        echo " "
        printf $Yellow"Please type -h or --help to see how it works"$NC
        echo " "
        exit 255
fi

##Main Function

#Setting Monioring box IP
if [ "${mbox}" == "DAL" ]; then
   monip="142.0.204.76"
elif [ "${mbox}" == "AMS" ]; then
   monip="172.255.235.68"
elif [ "${mbox}" == "MOS" ]; then
    monip="88.212.242.156"
elif [ "${mbox}" == "SIG" ]; then
    monip="103.23.210.188"
elif [ "${mbox}" == "SJ" ]; then
    monip="209.191.164.177"
elif [ "${mbox}" == "SYD" ]; then
    monip="135.90.89.184"
elif [ "${mbox}" == "SP" ]; then
    monip="169.57.142.117"
elif [ "${mbox}" == "WDC" ]; then
    monip="66.242.12.70"
elif [ "${mbox}" == "zbx-proxy-asia-east2-c" ]; then
    monip="34.96.175.93"
elif [ "${mbox}" == "zbx-proxy-asia-southeast1-c" ]; then
    monip="34.126.115.225"
elif [ "${mbox}" == "zbx-proxy-australia-southeast1-c" ]; then
    monip="34.116.91.115"
elif [ "${mbox}" == "zbx-proxy-europe-north1-c" ]; then
    monip="35.228.223.23"
elif [ "${mbox}" == "zbx-proxy-europe-west4-c" ]; then
    monip="34.91.110.45"
elif [ "${mbox}" == "zbx-proxy-southamerica-east1-c" ]; then
    monip="34.95.152.232"
elif [ "${mbox}" == "zbx-proxy-us-central1-c" ]; then
    monip="35.238.138.122"
elif [ "${mbox}" == "zbx-proxy-us-east4-a" ]; then
    monip="35.245.34.190"
elif [ "${mbox}" == "zbx-proxy-us-west2-c" ]; then
    monip="34.94.241.217"
elif [ "${mbox}" == "zbx-proxy-me-south-1" ]; then
    monip="15.185.203.38"
fi

printf "[I] You are using Monitor Box located in: ${Green}${mbox} ${monip}${NC}"
echo " "

SH_HOST="root@${IP}"
SH_DEST="root@${monip}"

printf "${Green}Result loading${NC}"
echo " "

echo " "
#Default is running all commands
if [ -z "$opt" ]; then
        mtr_chk()
        {
        src_result=$($SH $SH_HOST "mtr -wbrc 100 ${monip}"&)
        trg_result=$($SH $SH_DEST "mtr -wbrc 100 ${IP}"&)
        printf $Yellow
        echo "$src_result"
        echo " "
        echo "$trg_result"
        printf $NC

        }
        mtr_chk

fi

# Running Frequency Only Option

if [ "$opt" == "-T" ]; then
        tcp_chk()
        {
        tsrc_result=$($SH $SH_HOST "mtr -i 1.0 -wbc 50 -r -T ${monip}"&)
        ttrg_result=$($SH $SH_DEST "mtr -i 1.0 -wbc 50 -r -T ${IP}"&)
        printf $Yellow
        echo "$tsrc_result"
        echo " "
        echo "$ttrg_result"
        printf $NC
        }
        tcp_chk
fi

if [ "$opt" == "-U" ]; then
        ucp_chk()
        {
        usrc_result=$($SH $SH_HOST "mtr -i 1.0 -wbc 50 -r -u ${monip}"&)
        utrg_result=$($SH $SH_DEST "mtr -i 1.0 -wbc 50 -r -u ${IP}"&)
        printf $Yellow
        echo "$usrc_result"
        echo " "
        echo "$utrg_result"
        printf $NC
        }
        ucp_chk
fi
